name: CI

on:
  push:
  pull_request:

jobs:
  lint:
    name: Lint
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v7

      - name: Installer uv
        uses: astral-sh/setup-uv@v10.0.1

      - name: Installer les dépendances
        run: uv sync

      - name: Lancer le lint
        run: uv run ruff check .

  test:
    name: Test
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v7

      - name: Installer uv
        uses: astral-sh/setup-uv@v10.0.1

      - name: Installer les dépendances
        run: uv sync

      - name: Lancer les tests
        run: uv run pytest -v

  build:
    name: Build
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v7

      - name: Installer uv
        uses: astral-sh/setup-uv@v10.0.1

      - name: Installer les dépendances
        run: uv sync

      - name: Lancer le build
        run: uv build

        