name: CI

on:
  push:
  pull_request:

jobs:
  lint:
    name: Lint
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v7

      - name: Installer uv
        uses: astral-sh/setup-uv@v10.0.1

      - name: Installer les dépendances
        run: uv sync

      - name: Lancer le lint
        run: uv run ruff check .

      - name: Lancer le lint de formatage
        run: uv run ruff format --check .

  test:
    name: Test
    runs-on: ${{ matrix.os }}

    strategy:
      fail-fast: false
      matrix:
        os: [ubuntu-latest, windows-latest]
        python-version: ["3.12", "3.13", "3.14"]

    steps:
      - uses: actions/checkout@v7

      - name: Installer uv
        uses: astral-sh/setup-uv@v10.0.1

      - name: utilisé le cahe uv
        uses: actions/cache@v3
        with:
          path: ~/.cache/uv
          key: ${{ runner.os }}-uv-${{ hashFiles('**/uv.lock') }}
          restore-keys: |
            ${{ runner.os }}-uv-

      - name: Installer les dépendances
        run: uv sync

      - name: Lancer les tests et les couverture de code 
        run: uv run pytest -v --cov=fleet_api --cov-report=html

  build:
    name: Build
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v7

      - name: Installer uv
        uses: astral-sh/setup-uv@v10.0.1

      - name: Installer les dépendances
        run: uv sync

      - name: Lancer le build
        run: uv build

      - name: Sauvegarder le build
        uses: actions/upload-artifact@v7
        with:
          name: distribution
          path: dist/
          retention-days: 7
